build:
    version: 1.0.0
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:9008/eureka
info:
    app:
        description: Client service application
        name: client-service
        version: 1.0.0
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
server:
    port: 9006
spring:
    application:
        name: client-service
    config:
        import: configserver:http://localhost:9007/
    datasource:
        password: 12345678
        url: jdbc:mysql://localhost:3306/textile_db
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    profiles:
        active: dev
