server:
  port: 9005

spring:
  application:
    name: dispatch-service
  config:
    import: "configserver:http://localhost:9007/"
  datasource:
    url: jdbc:mysql://localhost:3306/textile_db
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: dispatch-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

# Custom application properties
app:
  client-service:
    url: http://localhost:9006
  notification-service:
    url: http://localhost:9004
management:
  info:
    env:
      enabled: true
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9008/eureka
info:
  app:
    name: "dispatch-service"
    description: "Dispatch service application"
    version: "1.0.0"