server:
  port: 9001
spring:
  application:
    name: inventory-service
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:9007/"
  # Spring Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/textile_db
    username: root
    password: 12345678
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  # Kafka Producer
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # This is CRITICAL for deserializing event DTOs
      properties:
        spring:
          json:
            trusted:
              packages: '*'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9008/eureka
info:
  app:
    name: "inventory-service"
    description: "Inventory service application"
    version: "1.0.0"